version: 2
updates:
  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: monthly
    groups:
      major:
        update-types:
          - major
      non-major:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      major:
        update-types:
          - major
      non-major:
        update-types:
          - minor
          - patch
